name: Cypress Cloud

on:
  workflow_dispatch:
    inputs: 
      spec:
        description: Run by command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: f459c6be-2754-4569-9fbc-c3a8e3e5375e
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
